stream {
    include /etc/nginx/snippets/ruconet-stream.conf;

    # Gitea (SSH)
    server {
        listen gitea.ruconet.internal:22 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        proxy_pass 127.0.0.1:2222;
        proxy_timeout 1h;
    }

    # PostgreSQL (Client)
    server {
        listen 127.0.0.1:5432;

        proxy_pass db.ruconet.internal:5432;
        proxy_timeout 12h;

        proxy_ssl on;
        include /etc/nginx/snippets/ruconet-proxy.conf;
    }
}
